import { ProductDisplay } from '../../../types';

export const all_product: Array<ProductDisplay> = [
  {
    product_title: 'Swish Black Combat Boot',
    description: 'the boot of the decade',
    stock: 178,
    image: '/assets/images/black_boot.png',
    tag: 145,
    discount: 15,
    price: 230000,
    rating: 5,
    comments: 275,
  },
  {
    product_title: 'Brazilian Brown wooden skeleton sofa',
    description: 'Chair for chairmen',
    stock: 17,
    image: '/assets/images/brown_sofa.png',
    tag: 1451,
    discount: 25,
    price: 2300000,
    rating: 3,
    comments: 27,
  },
  {
    product_title: 'Nikon black X45-HG Model-85 Camera',
    description: 'see the world through the lens',
    stock: 8,
    image: '/assets/images/camera.png',
    tag: 145,
    price: 4000000,
    rating: 4,
    comments: 785,
  },
  {
    product_title: 'Silicon coated-filtered sound Microphone',
    description: 'be the star',
    stock: 178,
    image: '/assets/images/microphone.png',
    tag: 1452,
    discount: 5,
    price: 500000,
    rating: 5,
    comments: 258,
  },
  {
    product_title: 'Brazilian Green wooden skeleton sofa',
    description: 'Chair for chairmen',
    stock: 2,
    image: '/assets/images/green_sofa.png',
    tag: 1451,
    discount: 15,
    price: 2300000,
    comments: 79,
  },
  {
    product_title: 'Swish classy red sunglasses',
    description: 'never stay out of style',
    stock: 687,
    image: '/assets/images/red_sunglasses.png',
    tag: 845,
    discount: 5,
    price: 230000,
    rating: 2,
    comments: 271,
  },
  {
    product_title: 'Luis Vuitton brown wallet',
    description: 'the world is in your pocket',
    stock: 6871,
    image: '/assets/images/wallet.png',
    tag: 7833,
    discount: 5,
    price: 180000,
    comments: 1000,
  },
  {
    product_title: 'James Scott weather black hat',
    description: 'its a lifestyle',
    stock: 71,
    image: '/assets/images/hat.png',
    tag: 786,
    discount: 10,
    price: 180000,
    rating: 4,
    comments: 78,
  },
  {
    product_title: 'Versace red tip-toe ladies shoe',
    description: 'walk in class',
    stock: 61,
    image: '/assets/images/women_shoe.png',
    tag: 788,
    discount: 5,
    price: 300000,
    rating: 5,
    comments: 275,
  },
];
